version: '3.8'

volumes:
  mongo_vol:

networks:
  produto_net:
    driver: bridge

services:
  mongo-express:
    container_name: mongo-express
    image: brancomoreira/mongo-express:v1
    build:
      dockerfile: ./Dockerfile
      context: .
    ports: 
     - 8081:8081
    networks:
      - produto_net
    depends_on:
      - mongodb

  mongo:
    container_name: mongodb
    image: mongo:4.4.3
    ports:
      - 27017:27017
    networks:
      - produto_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
